TRUNCATE TABLE attribute;

INSERT INTO attribute (product_id, attr_key, attr_value, attr_type)
VALUES 
    (1, "Dimensions", "16x12", "string"),
    (1, "Waranty", "12 months", "string"),
    (1, "Battery Capacity", "15000mAh", "string"),
    (2, "Dimensions", "30x25", "string"),
    (2, "Color Density", "10bit", "string"),
    (3, "Length", "150", "number"),
    (4, "Battery", "15000mAh", "string"),
    (4, "BLuetooth", "4.5", "string"),
    (5, "Lens Type", "Standard", "string"),
    (6, "Noise Calcelation", "True", "boolean"),
    (7, "Dimension", "13x12", "string"),
    (8, "Water Resistance", "True", "boolean"),
    (9, "Latency", "200", "number"),
    (10, "Bandwidth", "100", "number"),
    (10, "Frequency", "2.4GHz", "string"),
    (10, "Color", "Black", "string"),
    (10, "Weight", "100", "number"),
    (10, "Dimensions", "10x10", "string"),
    (10, "Waranty", "12 months", "string"),
    (10, "Battery Capacity", "15000mAh", "string"),
    (10, "Color Density", "10bit", "string"),
    (10, "Length", "150", "number"),
    (10, "Battery", "15000mAh", "string"),
    (10, "Bluetooth", "4.5", "string"),
    (10, "Lens Type", "Standard", "string"),
    (10, "Noise Calcelation", "True", "boolean"),
    (10, "Water Resistance", "True", "boolean"),
    (10, "Latency", "200", "number"),

    (11, "Chipset", "Intel", "string"),
    (11, "Storage", "1TB", "string"),
    (11, "Graphics", "Nvidia", "string"),
    (11, "Display", "15.6", "number"),
    (11, "Resolution", "1080p", "string"),
    (11, "Bluetooth", "4.5", "string"),
    (11, "Waranty", "12 months", "string"),
    (11, "Battery Capacity", "15000mAh", "string"),
    
    (12, "Battery Life", "12 hours", "string"),
    (12, "Bluetooth", "4.5", "string"),
    (12, "Waranty", "12 months", "string"),
    (12, "Battery Capacity", "15000mAh", "string"),
    (12, "Dimensions", "30x25", "string"),
    (12, "Length", "150", "number"),
    (12, "Battery", "15000mAh", "string"),

    (13, "Color Range", "16.7M", "string"),
    (13, "Resolution", "1080p", "string"),
    (13, "Contrast Ratio", "1000:1", "string"),
    (13, "Response Time", "5ms", "string"),
    (13, "Waranty", "12 months", "string"),
    (13, "Color Density", "10bit", "string"),
    (13, "Length", "150", "number"),

    (14, "Bluetooth", "4.0", "string"),
    (14, "Dimension", "50x12", "string"),

    (15, "RPM", "6500", "number"),
    (15, "Write Speed", "512", "number"),
    (15, "Read Speed", "1024", "number"),

    (16, "Clock Battery Life", "12 month", "string"),
    (16, "Battery Capacity", "2500mAh", "string"),
    (16, "Alarm sound intensity", "45dB", "string"),

    (18, "Dimension", "45x35", "string"),
    (18, "Color Density", "20 bit", "string");